repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-yaml
  - id: debug-statements
  - id: name-tests-test
  - id: double-quote-string-fixer
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
- hooks:
  - additional_dependencies:
    - flake8-typing-imports==1.10.0
    id: flake8
  repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
- hooks:
  - id: autopep8
  repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.7
- hooks:
  - args:
    - --py36-plus
    id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v2.29.1
- hooks:
  - args:
    - --py3-plus
    id: reorder-python-imports
  repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
- hooks:
  - args:
    - --py36-plus
    id: add-trailing-comma
  repo: https://github.com/asottile/add-trailing-comma
  rev: v2.2.1
- hooks:
  - additional_dependencies:
    - types-all
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.920
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.3
- hooks:
  - args:
    - requirements.in
    files: ^requirements\.(in|txt)$
    id: pip-compile
    name: pip-compile requirements.in
  - args:
    - dev-requirements.in
    files: ^dev-requirements\.(in|txt)$
    id: pip-compile
    name: pip-compile dev-requirements.in
  repo: https://github.com/jazzband/pip-tools
  rev: 5.3.1
